### ISSUE TITLE
error: Error: Unable to resolve module `./vpa-handles.json` from `node_modules\format-utils\dist\vpa.js`:

### ISSUE THREAD

**Issue by vibhorpahare** [mastermunj/format-utils#241]
![Screenshot (29)](https://user-images.githubusercontent.com/18512213/101813928-5f246380-3b43-11eb-952f-12aeaccc0e30.png)

**Comment by mastermunj** [comment]
Hi @vibhorpahare, thanks for using the package and reporting the issue.

I have fixed it in new release v0.0.5.
